version: "3.8"
services:
  mgmd:
    hostname: mgmd
    image: jerrylucid/mysql-cluster:arm64
    command: ["ndb_mgmd"]    
    volumes:
      - ./mgmd:/var/lib/mysql
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
        mysql-cluster:
          ipv4_address: 192.168.0.2

  ndb1:
    hostname: ndb1
    image: jerrylucid/mysql-cluster:arm64
    command: ["ndbd"]
    volumes:
      - ./ndb1:/var/lib/mysql
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
       mysql-cluster:
          ipv4_address: 192.168.0.3


  ndb2:
    hostname: ndb2
    image: jerrylucid/mysql-cluster:arm64
    command: ["ndbd"]
    volumes:
      - ./ndb2:/var/lib/mysql
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
       mysql-cluster:
          ipv4_address: 192.168.0.4

        
  sql1:
    hostname: sql1
    image: jerrylucid/mysql-cluster:arm64
    command: ["mysqld"]
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
    volumes:
      - ./sql1:/var/lib/mysql
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    ports:
      - "3306:3306"
    depends_on:
      - mgmd
    networks:
       mysql-cluster:
          ipv4_address: 192.168.0.10
        
  sql2:
    hostname: sql2
    image: jerrylucid/mysql-cluster:arm64
    command: ["mysqld"]
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
    volumes:
      - ./sql2:/var/lib/mysql
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    ports:
      - "3307:3306"
    depends_on:
      - mgmd
    networks:
       mysql-cluster:
          ipv4_address: 192.168.0.11

networks:
  mysql-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16  
    external: true
      